# True color settings
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# Statusbar

set-option -g status-style fg="#ffffff",bg="#5f5f5f"
set-option -g status-left-style fg="#ffffff",bg="#5f5f5f"
set-option -g status-right-style fg="#ffffff",bg="#5f5f5f"
set-option -g window-status-style fg="#ffffff",bg="#5f5f5f"
set-option -g window-status-current-style fg="#ffffff",bg="#5f5f5f"
set-option -g message-style fg="#ffffff",bg="#5f5f5f"

set-option -g status-position top

set -g status-right "#($HOME/.local/scripts/tmuxsb_git-branch.sh)"

# Keybinds

## Select-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## Prefix
unbind C-b
set-option -g prefix C-space
bind C-t send-prefix

## Splits
bind v split-window -h
bind s split-window -v

## Change session
bind , choose-session
