#!/bin/sh

MOUNT_POINT="$HOME/Nextcloud"
NOTES_DIR="$MOUNT_POINT/Notes"

if [ ! -d "$NOTES_DIR" ]; then
    mkdir -p "$MOUNT_POINT"
    rclone mount Nextcloud-Teb0so: "$MOUNT_POINT" --vfs-cache-mode writes --daemon

    i=0
    while [ ! -d "$NOTES_DIR" ] && [ $i -lt 10 ]; do
        sleep 1
        i=$((i + 1))
    done
fi

nvim "$NOTES_DIR"

