#!/usr/bin/env bash

max_tries=0
tries=0
cmd="$1"

pkill -- $cmd

while pgrep -- "$cmd" > /dev/null; do
    sleep 1;
    ((tries++))

    if (( tries == $max_tries )); then
        echo "Could not stop program $cmd" >&2
        exit 1
    fi
done

$cmd > /dev/null 2>&1 &
disown
