#!/usr/bin/env bash

shopt -s nullglob extglob

for file in *@(.zip|.rar|.7z); do
    ext="${file##*.}"
    dir="${file%.*}"

    [[ -d "$dir" && -n "$(ls -A "$dir" 2>/dev/null)" ]] && continue

    echo "Creating directory ${dir}..." && mkdir -p -- "$dir"

    case "$ext" in
        zip) echo "Extracting ${file} with unzip..." && unzip -- "$file" -d "$dir" ;;
        rar) echo "Extracting ${file} with unrar..." && unrar x -- "$file" "$dir/" ;;
        7z)  echo "Extracting ${file} with 7z..."    && 7z x "$file" -o"$dir" ;;
    esac
done
