[env]
term = "xterm-256color"

[colors.cursor]
text    = "#c0c0c0"
cursor  = "#000000"

[colors.primary]
background = "#c0c0c0"
foreground = "#000000"

[colors.normal]
black   = "#000000"
red     = "#af0000"
green   = "#008700"
yellow  = "#af5f00"
blue    = "#005faf"
magenta = "#870087"
cyan    = "#008787"
white   = "#8a8a8a"

[colors.bright]
black   = "#808080"
red     = "#d70000"
green   = "#5faf5f"
yellow  = "#d78700"
blue    = "#0087d7"
magenta = "#af00af"
cyan    = "#00afaf"
white   = "#ffffff"

[font]
size = 14

[font.normal]
family = "IosevkaTermSlabNerdFont"
style  = "Regular"

[font.bold]
family = "IosevkaTermSlabNerdFont"
style  = "Bold"

[font.italic]
family = "IosevkaTermSlabNerdFont"
style  = "Italic"

[window]
opacity = 0.93
