[env]
term = "xterm-256color"

[colors.cursor]
text    = "#ffffff"
cursor  = "#000000"

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.normal]
white   = '#888888'

[colors.selection]
text    = "#ffffff"
background = "#00aaff"

[font]
size = 14

[font.normal]
family = "IosevkaTermSlabNerdFont"
style  = "Regular"

[font.bold]
family = "IosevkaTermSlabNerdFont"
style  = "Bold"

[font.italic]
family = "IosevkaTermSlabNerdFont"
style  = "Italic"
