[env]
term = "xterm-256color"

[colors.cursor]
text    = "#1d1f21"
cursor  = "#c5c8c6"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black   = '#282a2e'
red     = '#a54242'
green   = '#8c9440'
yellow  = '#de935f'
blue    = '#5f819d'
magenta = '#85678f'
cyan    = '#5e8d87'
white   = '#707880'

[colors.bright]
black   = '#373b41'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#8abeb7'
white   = '#c5c8c6'

[colors.selection]
text    = "#c5c8c6"
background = "#373b41"

[font]
size = 14

[font.normal]
family = "IosevkaTermSlabNerdFont"
style  = "Regular"

[font.bold]
family = "IosevkaTermSlabNerdFont"
style  = "Bold"

[font.italic]
family = "IosevkaTermSlabNerdFont"
style  = "Italic"

[keyboard]
bindings = [
  { key = "X", mods = "Control|Shift", action = "ToggleViMode" },
]

[cursor]
vi_mode_style = { shape = "Block" , blinking = "Never" }

[window]
dimensions = {columns = 120, lines = 35 }
opacity = 0.95
